"""expand_projects

Revision ID: 9a029d86ac80
Revises: 038a8e04c74d
Create Date: 2026-03-06 03:51:04.009505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a029d86ac80'
down_revision: Union[str, None] = '038a8e04c74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_link', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('highlights', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'highlights')
    op.drop_column('projects', 'github_link')
    op.drop_column('projects', 'image_url')
    # ### end Alembic commands ###
